---
- hosts: db
  become: yes
  vars:
    db_packages:
      - mariadb-server
      - MySQL-python
    db_service: mariadb
    src_file: "/home/devops/lab2-files/my.cnf.template"
    dst_file: /etc/my.cnf
  tasks:
    - name: Install {{ db_packages }} package
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ db_packages }}"
      notify:
        - start_service
    - name: Download and install {{ dst_file }}
      copy:
        src: "{{ src_file }}"
        dest: "{{ dst_file }}"
        owner: mysql
        group: mysql
        force: yes
      notify:
        - restart_service
        - set_password
    - name: set the MYSQL password
      mysql_user:
        name: root 
        password:  redhat
  handlers:
    - name: start_service
      service:
        name: "{{ db_service }}"
        state: started
    - name: restart_service
      service:
        name: "{{ db_service }}"
        state: restarted
    - name: set_password
      mysql_user:
        name: root
        password: redhat
