---
- hosts: db
  become: yes
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Check {{ web_package }} installation status 
      command: yum list installed "{{ web_package }}"
      register: command_result
      ignore_errors: yes
    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest
      ignore_errors: yes

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest
      when:  " 'Error' in command_result_stdout" 
